routes:
    home:       'Default:home'
    logout:     'Security:logout'
    reglog:     'Security:reglog'
    user:       'User:user'
    contact:    'Default:contact'
    article:    'Default:article'
    admin:       'Security:admin'
    admin_users: 'Security:admin_users'
    admin_articles: 'Security:admin_articles'
    admin_comments: 'Security:admin_comments'
    add_article: 'Article:add_article'
    edit_article: 'Article:edit_article'


defaut_route: 'home'

db_config:
    name: 'cheikhomnqcoscos'
    host: 'cheikhomnqcoscos.mysql.db'
    user: 'cheikhomnqcoscos'
    pass: 'cosCOS9154'
